-- All-in-one Supabase setup for the Full AI Messenger chatbot.
-- Run this file in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- Connected Facebook Pages and AI business knowledge.
create table if not exists public.clients (
  id integer generated by default as identity primary key,
  client_name text not null,
  page_id text not null,
  page_access_token text not null,
  created_at timestamptz not null default now(),
  bot_type text not null default 'ai',
  business_info text not null default '',
  ai_enabled boolean not null default true,
  google_sheets_webhook_url text not null default '',
  lead_capture_fields text not null default 'Full Name
Phone',
  constraint clients_page_id_key unique (page_id)
);

alter table public.clients
  add column if not exists client_name text,
  add column if not exists page_id text,
  add column if not exists page_access_token text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists bot_type text not null default 'ai',
  add column if not exists business_info text not null default '',
  add column if not exists ai_enabled boolean not null default true,
  add column if not exists google_sheets_webhook_url text not null default '',
  add column if not exists lead_capture_fields text not null default 'Full Name
Phone';

update public.clients
set
  client_name = coalesce(client_name, ''),
  page_id = coalesce(page_id, ''),
  page_access_token = coalesce(page_access_token, ''),
  bot_type = 'ai',
  business_info = coalesce(business_info, ''),
  ai_enabled = coalesce(ai_enabled, true),
  google_sheets_webhook_url = coalesce(google_sheets_webhook_url, ''),
  lead_capture_fields = coalesce(nullif(lead_capture_fields, ''), 'Full Name
Phone');

alter table public.clients
  alter column client_name set not null,
  alter column page_id set not null,
  alter column page_access_token set not null,
  alter column created_at set default now(),
  alter column bot_type set default 'ai',
  alter column business_info set default '',
  alter column ai_enabled set default true,
  alter column google_sheets_webhook_url set default '',
  alter column lead_capture_fields set default 'Full Name
Phone',
  alter column bot_type set not null,
  alter column business_info set not null,
  alter column ai_enabled set not null,
  alter column google_sheets_webhook_url set not null,
  alter column lead_capture_fields set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'clients_page_id_key'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients add constraint clients_page_id_key unique (page_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'clients_bot_type_ai_only_check'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients add constraint clients_bot_type_ai_only_check check (bot_type = 'ai');
  end if;
end $$;

create index if not exists clients_created_at_idx
  on public.clients (created_at);

-- Messenger send/usage logs.
create table if not exists public.rate_limit_logs (
  id integer generated by default as identity primary key,
  client_id text not null,
  page_id text not null,
  recipient_id text not null,
  message_type text not null,
  attempt_number integer not null default 0,
  status_code integer not null,
  error_code integer,
  error_subcode integer,
  error_message text not null,
  x_app_usage text,
  x_page_usage text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.rate_limit_logs
  add column if not exists client_id text not null default '',
  add column if not exists page_id text not null default '',
  add column if not exists recipient_id text not null default '',
  add column if not exists message_type text not null default '',
  add column if not exists attempt_number integer not null default 0,
  add column if not exists status_code integer not null default 0,
  add column if not exists error_code integer,
  add column if not exists error_subcode integer,
  add column if not exists error_message text not null default '',
  add column if not exists x_app_usage text,
  add column if not exists x_page_usage text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

create index if not exists rate_limit_logs_created_at_idx
  on public.rate_limit_logs (created_at);

create index if not exists rate_limit_logs_client_created_at_idx
  on public.rate_limit_logs (client_id, created_at desc);

create index if not exists rate_limit_logs_page_created_at_idx
  on public.rate_limit_logs (page_id, created_at desc);

-- Customer conversation state and owner handoff.
create table if not exists public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  last_customer_message text,
  last_message_at timestamptz,
  ai_paused boolean not null default false,
  paused_at timestamptz,
  paused_by text,
  resumed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_conversations_client_recipient_key unique (client_id, recipient_id)
);

alter table public.ai_conversations
  add column if not exists client_id integer,
  add column if not exists page_id text not null default '',
  add column if not exists recipient_id text not null default '',
  add column if not exists last_customer_message text,
  add column if not exists last_message_at timestamptz,
  add column if not exists ai_paused boolean not null default false,
  add column if not exists paused_at timestamptz,
  add column if not exists paused_by text,
  add column if not exists resumed_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists ai_conversations_client_last_message_idx
  on public.ai_conversations (client_id, last_message_at desc);

create index if not exists ai_conversations_client_paused_idx
  on public.ai_conversations (client_id, ai_paused);

-- Business owner access mapping. Supabase Auth users are not stored here.
create table if not exists public.business_users (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  email text not null,
  role text not null default 'owner',
  created_at timestamptz not null default now(),
  constraint business_users_email_key unique (email),
  constraint business_users_role_check check (role in ('owner'))
);

alter table public.business_users
  add column if not exists client_id integer,
  add column if not exists email text not null default '',
  add column if not exists role text not null default 'owner',
  add column if not exists created_at timestamptz not null default now();

create index if not exists business_users_client_id_idx
  on public.business_users (client_id);

-- Order queue shown in the business-owner portal.
create table if not exists public.orders (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  customer_name text,
  contact_number text,
  order_summary text not null,
  status text not null default 'pending',
  total_amount numeric(12, 2),
  payment_method text,
  delivery_method text,
  delivery_address text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_status_check check (status in ('pending', 'confirmed', 'completed', 'cancelled'))
);

alter table public.orders
  add column if not exists client_id integer,
  add column if not exists page_id text not null default '',
  add column if not exists recipient_id text not null default '',
  add column if not exists customer_name text,
  add column if not exists contact_number text,
  add column if not exists order_summary text not null default '',
  add column if not exists status text not null default 'pending',
  add column if not exists total_amount numeric(12, 2),
  add column if not exists payment_method text,
  add column if not exists delivery_method text,
  add column if not exists delivery_address text,
  add column if not exists notes text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists orders_client_created_at_idx
  on public.orders (client_id, created_at desc);

create index if not exists orders_client_status_idx
  on public.orders (client_id, status);

-- Drop tables from removed legacy features.
drop table if exists public.bot_flow_reply_sessions;
drop table if exists public.faqs;
drop table if exists public.replied_comments;

-- Locked-down RLS baseline. Server API routes use the service role key.
alter table public.clients enable row level security;
alter table public.rate_limit_logs enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.business_users enable row level security;
alter table public.orders enable row level security;

revoke all on table public.clients from anon, authenticated;
revoke all on table public.rate_limit_logs from anon, authenticated;
revoke all on table public.ai_conversations from anon, authenticated;
revoke all on table public.business_users from anon, authenticated;
revoke all on table public.orders from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
