-- All-in-one Supabase setup for this app.
-- Run this single file instead of running 01 through 07 individually.
-- It is ordered to create tables first, then apply RLS lockdown.


-- ============================================================
-- supabase\01-core-schema.sql
-- ============================================================

-- Core tables used by the dashboard, Facebook connection flow, and Full AI prompt builder.
-- Run this first.

create extension if not exists pgcrypto;

create table if not exists public.clients (
  id integer generated by default as identity primary key,
  client_name text not null,
  page_id text not null,
  page_access_token text not null,
  created_at timestamptz not null default now(),
  bot_type text not null default 'ai',
  business_info text not null default '',
  constraint clients_page_id_key unique (page_id)
);

alter table public.clients
  add column if not exists client_name text;

alter table public.clients
  add column if not exists page_id text;

alter table public.clients
  add column if not exists page_access_token text;

alter table public.clients
  add column if not exists created_at timestamptz not null default now();

alter table public.clients
  add column if not exists bot_type text not null default 'ai';

alter table public.clients
  add column if not exists business_info text not null default '';

update public.clients
set client_name = ''
where client_name is null;

update public.clients
set page_id = ''
where page_id is null;

update public.clients
set page_access_token = ''
where page_access_token is null;

alter table public.clients
  alter column client_name set not null;

alter table public.clients
  alter column page_id set not null;

alter table public.clients
  alter column page_access_token set not null;

alter table public.clients
  alter column created_at set default now();

alter table public.clients
  alter column bot_type set default 'ai';

alter table public.clients
  alter column business_info set default '';

update public.clients
set bot_type = 'ai'
where bot_type is distinct from 'ai';

update public.clients
set business_info = ''
where business_info is null;

alter table public.clients
  alter column bot_type set not null;

alter table public.clients
  alter column business_info set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'clients_page_id_key'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients
      add constraint clients_page_id_key unique (page_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'clients_bot_type_ai_only_check'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients
      add constraint clients_bot_type_ai_only_check check (bot_type = 'ai');
  end if;
end $$;

create index if not exists clients_created_at_idx
  on public.clients (created_at);

create table if not exists public.faqs (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  keywords text[] not null default '{}',
  answer text not null,
  image_attachment_id text,
  created_at timestamptz not null default now()
);

alter table public.faqs
  add column if not exists client_id integer;

alter table public.faqs
  add column if not exists keywords text[] not null default '{}';

alter table public.faqs
  add column if not exists answer text not null default '';

alter table public.faqs
  add column if not exists image_attachment_id text;

alter table public.faqs
  add column if not exists created_at timestamptz not null default now();

create index if not exists faqs_client_created_at_idx
  on public.faqs (client_id, created_at);

-- ============================================================
-- supabase\02-legacy-flow-support.sql
-- ============================================================

-- Legacy keyword/flow support tables.
-- The current product is Full AI only, but these tables are still referenced by
-- debug/cleanup code and older webhook helper paths. Keep them until the legacy
-- flow APIs are fully removed.

create table if not exists public.bot_flow_reply_sessions (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  waiting_node_id text not null,
  next_node_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bot_flow_reply_sessions_client_recipient_key unique (client_id, recipient_id)
);

alter table public.bot_flow_reply_sessions
  add column if not exists client_id integer;

alter table public.bot_flow_reply_sessions
  add column if not exists page_id text not null default '';

alter table public.bot_flow_reply_sessions
  add column if not exists recipient_id text not null default '';

alter table public.bot_flow_reply_sessions
  add column if not exists waiting_node_id text not null default '';

alter table public.bot_flow_reply_sessions
  add column if not exists next_node_id text not null default '';

alter table public.bot_flow_reply_sessions
  add column if not exists created_at timestamptz not null default now();

alter table public.bot_flow_reply_sessions
  add column if not exists updated_at timestamptz not null default now();

create index if not exists bot_flow_reply_sessions_updated_at_idx
  on public.bot_flow_reply_sessions (updated_at);

create index if not exists bot_flow_reply_sessions_client_updated_at_idx
  on public.bot_flow_reply_sessions (client_id, updated_at desc);

-- ============================================================
-- supabase\03-logging-maintenance.sql
-- ============================================================

-- Messenger send/usage logs used by webhook rate-limit handling and the
-- dashboard storage cleanup endpoint.

create table if not exists public.rate_limit_logs (
  id integer generated by default as identity primary key,
  client_id text not null,
  page_id text not null,
  recipient_id text not null,
  message_type text not null,
  attempt_number integer not null default 0,
  status_code integer not null,
  error_code integer,
  error_subcode integer,
  error_message text not null,
  x_app_usage text,
  x_page_usage text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.rate_limit_logs
  add column if not exists client_id text not null default '';

alter table public.rate_limit_logs
  add column if not exists page_id text not null default '';

alter table public.rate_limit_logs
  add column if not exists recipient_id text not null default '';

alter table public.rate_limit_logs
  add column if not exists message_type text not null default '';

alter table public.rate_limit_logs
  add column if not exists attempt_number integer not null default 0;

alter table public.rate_limit_logs
  add column if not exists status_code integer not null default 0;

alter table public.rate_limit_logs
  add column if not exists error_code integer;

alter table public.rate_limit_logs
  add column if not exists error_subcode integer;

alter table public.rate_limit_logs
  add column if not exists error_message text not null default '';

alter table public.rate_limit_logs
  add column if not exists x_app_usage text;

alter table public.rate_limit_logs
  add column if not exists x_page_usage text;

alter table public.rate_limit_logs
  add column if not exists payload jsonb not null default '{}'::jsonb;

alter table public.rate_limit_logs
  add column if not exists created_at timestamptz not null default now();

create index if not exists rate_limit_logs_created_at_idx
  on public.rate_limit_logs (created_at);

create index if not exists rate_limit_logs_client_created_at_idx
  on public.rate_limit_logs (client_id, created_at desc);

create index if not exists rate_limit_logs_page_created_at_idx
  on public.rate_limit_logs (page_id, created_at desc);

-- ============================================================
-- supabase\04-ai-conversations.sql
-- ============================================================

-- Owner handoff / AI pause state.
-- Used by /dashboard/clients/[id]/conversations and by the Messenger webhook.

create table if not exists public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  last_customer_message text,
  last_message_at timestamptz,
  ai_paused boolean not null default false,
  paused_at timestamptz,
  paused_by text,
  resumed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_conversations_client_recipient_key unique (client_id, recipient_id)
);

alter table public.ai_conversations
  add column if not exists client_id integer;

alter table public.ai_conversations
  add column if not exists page_id text not null default '';

alter table public.ai_conversations
  add column if not exists recipient_id text not null default '';

alter table public.ai_conversations
  add column if not exists last_customer_message text;

alter table public.ai_conversations
  add column if not exists ai_paused boolean not null default false;

alter table public.ai_conversations
  add column if not exists paused_at timestamptz;

alter table public.ai_conversations
  add column if not exists paused_by text;

alter table public.ai_conversations
  add column if not exists resumed_at timestamptz;

alter table public.ai_conversations
  add column if not exists created_at timestamptz not null default now();

alter table public.ai_conversations
  add column if not exists updated_at timestamptz not null default now();

alter table public.ai_conversations
  add column if not exists last_message_at timestamptz;

create index if not exists ai_conversations_client_last_message_idx
  on public.ai_conversations (client_id, last_message_at desc);

create index if not exists ai_conversations_client_paused_idx
  on public.ai_conversations (client_id, ai_paused);

-- ============================================================
-- supabase\05-business-users.sql
-- ============================================================

-- Business owner access.
-- Admin users are still controlled by SUPABASE_ADMIN_EMAILS. Business owners
-- are Supabase Auth users whose email appears here and is assigned to a client.

create table if not exists public.business_users (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  email text not null,
  role text not null default 'owner',
  created_at timestamptz not null default now(),
  constraint business_users_email_key unique (email),
  constraint business_users_role_check check (role in ('owner'))
);

alter table public.business_users
  add column if not exists client_id integer;

alter table public.business_users
  add column if not exists email text not null default '';

alter table public.business_users
  add column if not exists role text not null default 'owner';

alter table public.business_users
  add column if not exists created_at timestamptz not null default now();

create index if not exists business_users_client_id_idx
  on public.business_users (client_id);

-- Add business owners like this after creating their Supabase Auth user:
-- insert into public.business_users (client_id, email)
-- values (1, 'owner@example.com')
-- on conflict (email) do update set client_id = excluded.client_id;

-- ============================================================
-- supabase\06-orders.sql
-- ============================================================

-- Orders table for the business-owner order view.
-- The AI order-taking workflow can insert confirmed orders here later.

create table if not exists public.orders (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  customer_name text,
  contact_number text,
  order_summary text not null,
  status text not null default 'pending',
  total_amount numeric(12, 2),
  payment_method text,
  delivery_method text,
  delivery_address text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_status_check check (status in ('pending', 'confirmed', 'completed', 'cancelled'))
);

alter table public.orders
  add column if not exists client_id integer;

alter table public.orders
  add column if not exists page_id text not null default '';

alter table public.orders
  add column if not exists recipient_id text not null default '';

alter table public.orders
  add column if not exists customer_name text;

alter table public.orders
  add column if not exists contact_number text;

alter table public.orders
  add column if not exists order_summary text not null default '';

alter table public.orders
  add column if not exists status text not null default 'pending';

alter table public.orders
  add column if not exists total_amount numeric(12, 2);

alter table public.orders
  add column if not exists payment_method text;

alter table public.orders
  add column if not exists delivery_method text;

alter table public.orders
  add column if not exists delivery_address text;

alter table public.orders
  add column if not exists notes text;

alter table public.orders
  add column if not exists created_at timestamptz not null default now();

alter table public.orders
  add column if not exists updated_at timestamptz not null default now();

create index if not exists orders_client_created_at_idx
  on public.orders (client_id, created_at desc);

create index if not exists orders_client_status_idx
  on public.orders (client_id, status);

-- ============================================================
-- supabase\07-rls-lockdown.sql
-- ============================================================

-- Locked-down RLS baseline.
-- The Next.js server uses SUPABASE_SERVICE_ROLE_KEY for database access after
-- app-level admin checks. Browser clients should not read/write app tables
-- directly, so this file enables RLS and removes direct anon/authenticated
-- table privileges.

alter table public.clients enable row level security;
alter table public.faqs enable row level security;
alter table public.bot_flow_reply_sessions enable row level security;
alter table public.rate_limit_logs enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.business_users enable row level security;
alter table public.orders enable row level security;

revoke all on table public.clients from anon, authenticated;
revoke all on table public.faqs from anon, authenticated;
revoke all on table public.bot_flow_reply_sessions from anon, authenticated;
revoke all on table public.rate_limit_logs from anon, authenticated;
revoke all on table public.ai_conversations from anon, authenticated;
revoke all on table public.business_users from anon, authenticated;
revoke all on table public.orders from anon, authenticated;

revoke all on all sequences in schema public from anon, authenticated;
