-- All-in-one Supabase setup for the Full AI Messenger chatbot.
-- Run this file in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- Connected Facebook Pages and AI business knowledge.
create table if not exists public.clients (
  id integer generated by default as identity primary key,
  client_name text not null,
  page_id text not null,
  page_access_token text not null,
  created_at timestamptz not null default now(),
  bot_type text not null default 'ai',
  business_info text not null default '',
  ai_enabled boolean not null default true,
  google_sheets_webhook_url text not null default '',
  google_sheets_tab_name text not null default 'Sheet1',
  lead_capture_fields text not null default 'Full Name
Phone',
  lead_capture_messages text not null default '',
  welcome_sequence_enabled boolean not null default false,
  welcome_message text not null default '',
  welcome_link_url text not null default '',
  welcome_image_urls text not null default '',
  manual_ai_pause_minutes integer not null default 5,
  auto_reply_ignore_pattern text not null default '',
  constraint clients_page_id_key unique (page_id)
);

alter table public.clients
  add column if not exists client_name text,
  add column if not exists page_id text,
  add column if not exists page_access_token text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists bot_type text not null default 'ai',
  add column if not exists business_info text not null default '',
  add column if not exists ai_enabled boolean not null default true,
  add column if not exists google_sheets_webhook_url text not null default '',
  add column if not exists google_sheets_tab_name text not null default 'Sheet1',
  add column if not exists lead_capture_fields text not null default 'Full Name
Phone',
  add column if not exists lead_capture_messages text not null default '',
  add column if not exists welcome_sequence_enabled boolean not null default false,
  add column if not exists welcome_message text not null default '',
  add column if not exists welcome_link_url text not null default '',
  add column if not exists welcome_image_urls text not null default '',
  add column if not exists manual_ai_pause_minutes integer not null default 5,
  add column if not exists auto_reply_ignore_pattern text not null default '';

update public.clients
set
  client_name = coalesce(client_name, ''),
  page_id = coalesce(page_id, ''),
  page_access_token = coalesce(page_access_token, ''),
  bot_type = 'ai',
  business_info = coalesce(business_info, ''),
  ai_enabled = coalesce(ai_enabled, true),
  google_sheets_webhook_url = coalesce(google_sheets_webhook_url, ''),
  google_sheets_tab_name = coalesce(nullif(google_sheets_tab_name, ''), 'Sheet1'),
  lead_capture_fields = coalesce(nullif(lead_capture_fields, ''), 'Full Name
Phone'),
  lead_capture_messages = coalesce(lead_capture_messages, ''),
  welcome_sequence_enabled = coalesce(welcome_sequence_enabled, false),
  welcome_message = coalesce(welcome_message, ''),
  welcome_link_url = coalesce(welcome_link_url, ''),
  welcome_image_urls = coalesce(welcome_image_urls, ''),
  manual_ai_pause_minutes = coalesce(manual_ai_pause_minutes, 5),
  auto_reply_ignore_pattern = coalesce(auto_reply_ignore_pattern, '');

alter table public.clients
  alter column client_name set not null,
  alter column page_id set not null,
  alter column page_access_token set not null,
  alter column created_at set default now(),
  alter column bot_type set default 'ai',
  alter column business_info set default '',
  alter column ai_enabled set default true,
  alter column google_sheets_webhook_url set default '',
  alter column google_sheets_tab_name set default 'Sheet1',
  alter column lead_capture_fields set default 'Full Name
Phone',
  alter column lead_capture_messages set default '',
  alter column bot_type set not null,
  alter column business_info set not null,
  alter column ai_enabled set not null,
  alter column google_sheets_webhook_url set not null,
  alter column google_sheets_tab_name set not null,
  alter column lead_capture_fields set not null,
  alter column lead_capture_messages set not null,
  alter column welcome_sequence_enabled set default false,
  alter column welcome_message set default '',
  alter column welcome_link_url set default '',
  alter column welcome_image_urls set default '',
  alter column manual_ai_pause_minutes set default 5,
  alter column auto_reply_ignore_pattern set default '',
  alter column welcome_sequence_enabled set not null,
  alter column welcome_message set not null,
  alter column welcome_link_url set not null,
  alter column welcome_image_urls set not null,
  alter column manual_ai_pause_minutes set not null,
  alter column auto_reply_ignore_pattern set not null;

alter table public.clients
  drop column if exists ai_character,
  drop column if exists ai_tone;

-- Confirmed lead capture configuration and retry-safe lead records.
alter table public.clients
  add column if not exists lead_capture_enabled boolean not null default false,
  add column if not exists lead_capture_fields text not null default 'Full Name|name\nPhone|phone',
  add column if not exists lead_capture_trigger text not null default '',
  add column if not exists lead_capture_offer text not null default '';

create table if not exists public.lead_records (
  id uuid primary key default gen_random_uuid(),
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  fields jsonb not null default '{}'::jsonb,
  field_config jsonb not null default '[]'::jsonb,
  status text not null default 'collecting',
  delivery_attempts integer not null default 0,
  last_delivery_error text not null default '',
  confirmed_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lead_records_status_check check (status in ('collecting', 'awaiting_confirmation', 'confirmed', 'delivered', 'delivery_failed'))
);

create index if not exists lead_records_open_by_customer_idx
  on public.lead_records (client_id, recipient_id, created_at desc)
  where status in ('collecting', 'awaiting_confirmation');
create index if not exists lead_records_delivery_retry_idx
  on public.lead_records (status, updated_at)
  where status in ('confirmed', 'delivery_failed');
alter table public.lead_records enable row level security;
revoke all on table public.lead_records from anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'clients_page_id_key'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients add constraint clients_page_id_key unique (page_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'clients_bot_type_ai_only_check'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients add constraint clients_bot_type_ai_only_check check (bot_type = 'ai');
  end if;
end $$;

create index if not exists clients_created_at_idx
  on public.clients (created_at);

-- Messenger send/usage logs.
create table if not exists public.rate_limit_logs (
  id integer generated by default as identity primary key,
  client_id text not null,
  page_id text not null,
  recipient_id text not null,
  message_type text not null,
  attempt_number integer not null default 0,
  status_code integer not null,
  error_code integer,
  error_subcode integer,
  error_message text not null,
  x_app_usage text,
  x_page_usage text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.rate_limit_logs
  add column if not exists client_id text not null default '',
  add column if not exists page_id text not null default '',
  add column if not exists recipient_id text not null default '',
  add column if not exists message_type text not null default '',
  add column if not exists attempt_number integer not null default 0,
  add column if not exists status_code integer not null default 0,
  add column if not exists error_code integer,
  add column if not exists error_subcode integer,
  add column if not exists error_message text not null default '',
  add column if not exists x_app_usage text,
  add column if not exists x_page_usage text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default now();

create index if not exists rate_limit_logs_created_at_idx
  on public.rate_limit_logs (created_at);

create index if not exists rate_limit_logs_client_created_at_idx
  on public.rate_limit_logs (client_id, created_at desc);

create index if not exists rate_limit_logs_page_created_at_idx
  on public.rate_limit_logs (page_id, created_at desc);

-- Customer conversation state and human handoff.
create table if not exists public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  last_customer_message text,
  last_ai_reply text,
  conversation_summary text not null default '',
  customer_state jsonb not null default '{}'::jsonb,
  recent_messages jsonb not null default '[]'::jsonb,
  welcome_sequence_sent boolean not null default false,
  last_message_at timestamptz,
  ai_paused boolean not null default false,
  paused_at timestamptz,
  paused_by text,
  ai_pause_expires_at timestamptz,
  resumed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_conversations_client_recipient_key unique (client_id, recipient_id)
);

alter table public.ai_conversations
  add column if not exists client_id integer,
  add column if not exists page_id text not null default '',
  add column if not exists recipient_id text not null default '',
  add column if not exists last_customer_message text,
  add column if not exists last_ai_reply text,
  add column if not exists conversation_summary text not null default '',
  add column if not exists customer_state jsonb not null default '{}'::jsonb,
  add column if not exists recent_messages jsonb not null default '[]'::jsonb,
  add column if not exists welcome_sequence_sent boolean not null default false,
  add column if not exists last_message_at timestamptz,
  add column if not exists ai_paused boolean not null default false,
  add column if not exists paused_at timestamptz,
  add column if not exists paused_by text,
  add column if not exists ai_pause_expires_at timestamptz,
  add column if not exists resumed_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists ai_conversations_client_last_message_idx
  on public.ai_conversations (client_id, last_message_at desc);

create index if not exists ai_conversations_client_paused_idx
  on public.ai_conversations (client_id, ai_paused);

create index if not exists ai_conversations_last_message_at_idx
  on public.ai_conversations (last_message_at);

-- Permanent minimal welcome receipt state.
create table if not exists public.welcome_sequence_recipients (
  id uuid primary key default gen_random_uuid(),
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  first_sent_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint welcome_sequence_recipients_client_recipient_key unique (client_id, recipient_id)
);

create index if not exists welcome_sequence_recipients_client_idx
  on public.welcome_sequence_recipients (client_id, updated_at desc);

insert into public.welcome_sequence_recipients (
  client_id,
  page_id,
  recipient_id,
  first_sent_at,
  updated_at
)
select
  client_id,
  page_id,
  recipient_id,
  coalesce(last_message_at, created_at, now()),
  coalesce(updated_at, last_message_at, now())
from public.ai_conversations
where welcome_sequence_sent = true
on conflict (client_id, recipient_id) do update
set
  page_id = excluded.page_id,
  updated_at = greatest(public.welcome_sequence_recipients.updated_at, excluded.updated_at);

-- Durable queue for Messenger webhook deliveries.
create table if not exists public.ai_message_jobs (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'messenger_webhook',
  body_hash text not null,
  payload jsonb not null,
  status text not null default 'queued',
  attempts integer not null default 0,
  max_attempts integer not null default 5,
  locked_at timestamptz,
  locked_by text,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_message_jobs_body_hash_key unique (body_hash),
  constraint ai_message_jobs_status_check check (
    status in ('queued', 'processing', 'retrying', 'sent', 'failed', 'canceled')
  )
);

alter table public.ai_message_jobs
  add column if not exists source text not null default 'messenger_webhook',
  add column if not exists body_hash text,
  add column if not exists payload jsonb not null default '{}'::jsonb,
  add column if not exists status text not null default 'queued',
  add column if not exists attempts integer not null default 0,
  add column if not exists max_attempts integer not null default 5,
  add column if not exists locked_at timestamptz,
  add column if not exists locked_by text,
  add column if not exists next_attempt_at timestamptz not null default now(),
  add column if not exists last_error text,
  add column if not exists processed_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

update public.ai_message_jobs
set
  source = coalesce(source, 'messenger_webhook'),
  body_hash = coalesce(body_hash, encode(digest(id::text, 'sha256'), 'hex')),
  payload = coalesce(payload, '{}'::jsonb),
  status = coalesce(status, 'queued'),
  attempts = coalesce(attempts, 0),
  max_attempts = coalesce(max_attempts, 5),
  next_attempt_at = coalesce(next_attempt_at, now()),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, now());

alter table public.ai_message_jobs
  alter column source set default 'messenger_webhook',
  alter column source set not null,
  alter column body_hash set not null,
  alter column payload set default '{}'::jsonb,
  alter column payload set not null,
  alter column status set default 'queued',
  alter column status set not null,
  alter column attempts set default 0,
  alter column attempts set not null,
  alter column max_attempts set default 5,
  alter column max_attempts set not null,
  alter column next_attempt_at set default now(),
  alter column next_attempt_at set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'ai_message_jobs_body_hash_key'
      and conrelid = 'public.ai_message_jobs'::regclass
  ) then
    alter table public.ai_message_jobs
      add constraint ai_message_jobs_body_hash_key unique (body_hash);
  end if;

  alter table public.ai_message_jobs
    drop constraint if exists ai_message_jobs_status_check;

  alter table public.ai_message_jobs
    add constraint ai_message_jobs_status_check check (
      status in ('queued', 'processing', 'retrying', 'sent', 'failed', 'canceled')
    );
end $$;

create index if not exists ai_message_jobs_ready_idx
  on public.ai_message_jobs (status, next_attempt_at, created_at)
  where status in ('queued', 'retrying');

create index if not exists ai_message_jobs_locked_idx
  on public.ai_message_jobs (locked_at)
  where status = 'processing';

create index if not exists ai_message_jobs_sent_processed_at_idx
  on public.ai_message_jobs (processed_at)
  where status = 'sent';

create index if not exists ai_message_jobs_terminal_processed_at_idx
  on public.ai_message_jobs (status, processed_at)
  where status in ('sent', 'failed', 'canceled');

-- Message-level dedupe for Messenger webhook retries.
create table if not exists public.processed_messenger_messages (
  id uuid primary key default gen_random_uuid(),
  event_key text not null,
  page_id text not null,
  recipient_id text not null,
  message_id text not null,
  created_at timestamptz not null default now(),
  constraint processed_messenger_messages_event_key_key unique (event_key)
);

create index if not exists processed_messenger_messages_created_at_idx
  on public.processed_messenger_messages (created_at);

create index if not exists processed_messenger_messages_page_recipient_idx
  on public.processed_messenger_messages (page_id, recipient_id, created_at desc);

create or replace function public.claim_ai_message_jobs(
  batch_size integer default 5,
  worker_id text default 'worker'
)
returns setof public.ai_message_jobs
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.ai_message_jobs
  set
    status = 'retrying',
    locked_at = null,
    locked_by = null,
    next_attempt_at = now(),
    updated_at = now()
  where status = 'processing'
    and locked_at < now() - interval '5 minutes'
    and attempts < max_attempts;

  return query
  with picked as (
    select id
    from public.ai_message_jobs
    where status in ('queued', 'retrying')
      and next_attempt_at <= now()
      and attempts < max_attempts
    order by created_at
    limit greatest(1, least(coalesce(batch_size, 5), 25))
    for update skip locked
  )
  update public.ai_message_jobs job
  set
    status = 'processing',
    attempts = job.attempts + 1,
    locked_at = now(),
    locked_by = coalesce(worker_id, 'worker'),
    updated_at = now()
  from picked
  where job.id = picked.id
  returning job.*;
end;
$$;

create or replace function public.cancel_pending_ai_message_jobs(
  target_page_id text,
  target_recipient_id text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  canceled_count integer := 0;
begin
  update public.ai_message_jobs job
  set
    status = 'canceled',
    locked_at = null,
    locked_by = null,
    last_error = 'Canceled because the Page owner manually replied.',
    processed_at = now(),
    updated_at = now()
  where job.status in ('queued', 'retrying')
    and exists (
      select 1
      from jsonb_array_elements(coalesce(job.payload->'entry', '[]'::jsonb)) entry
      cross join jsonb_array_elements(coalesce(entry->'messaging', '[]'::jsonb)) messaging
      where entry->>'id' = target_page_id
        and messaging->'sender'->>'id' = target_recipient_id
        and messaging->'message'->>'text' is not null
        and coalesce((messaging->'message'->>'is_echo')::boolean, false) = false
    );

  get diagnostics canceled_count = row_count;

  return canceled_count;
end;
$$;

create or replace function public.cleanup_ai_message_jobs()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer := 0;
begin
  delete from public.ai_message_jobs
  where (
      status in ('sent', 'canceled')
      and processed_at < now() - interval '1 day'
    )
    or (
      status = 'failed'
      and updated_at < now() - interval '7 days'
    );

  get diagnostics deleted_count = row_count;

  return deleted_count;
end;
$$;

-- Drop tables from removed legacy features.
drop table if exists public.orders;
drop table if exists public.business_users;
drop table if exists public.bot_flow_reply_sessions;
drop table if exists public.faqs;
drop table if exists public.replied_comments;

-- Locked-down RLS baseline. Server API routes use the service role key.
alter table public.clients enable row level security;
alter table public.rate_limit_logs enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.welcome_sequence_recipients enable row level security;
alter table public.ai_message_jobs enable row level security;
alter table public.processed_messenger_messages enable row level security;

revoke all on table public.clients from anon, authenticated;
revoke all on table public.rate_limit_logs from anon, authenticated;
revoke all on table public.ai_conversations from anon, authenticated;
revoke all on table public.welcome_sequence_recipients from anon, authenticated;
revoke all on table public.ai_message_jobs from anon, authenticated;
revoke all on table public.processed_messenger_messages from anon, authenticated;
revoke execute on function public.claim_ai_message_jobs(integer, text) from anon, authenticated;
revoke execute on function public.cancel_pending_ai_message_jobs(text, text) from anon, authenticated;
revoke execute on function public.cleanup_ai_message_jobs() from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
