-- Core client table used by the dashboard, Facebook connection flow, and AI prompt builder.

create extension if not exists pgcrypto;

create table if not exists public.clients (
  id integer generated by default as identity primary key,
  client_name text not null,
  page_id text not null,
  page_access_token text not null,
  created_at timestamptz not null default now(),
  bot_type text not null default 'ai',
  business_info text not null default '',
  ai_enabled boolean not null default true,
  google_sheets_webhook_url text not null default '',
  constraint clients_page_id_key unique (page_id)
);

alter table public.clients
  add column if not exists client_name text,
  add column if not exists page_id text,
  add column if not exists page_access_token text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists bot_type text not null default 'ai',
  add column if not exists business_info text not null default '',
  add column if not exists ai_enabled boolean not null default true,
  add column if not exists google_sheets_webhook_url text not null default '';

update public.clients
set
  client_name = coalesce(client_name, ''),
  page_id = coalesce(page_id, ''),
  page_access_token = coalesce(page_access_token, ''),
  bot_type = 'ai',
  business_info = coalesce(business_info, ''),
  ai_enabled = coalesce(ai_enabled, true),
  google_sheets_webhook_url = coalesce(google_sheets_webhook_url, '');

alter table public.clients
  alter column client_name set not null,
  alter column page_id set not null,
  alter column page_access_token set not null,
  alter column created_at set default now(),
  alter column bot_type set default 'ai',
  alter column business_info set default '',
  alter column ai_enabled set default true,
  alter column google_sheets_webhook_url set default '',
  alter column bot_type set not null,
  alter column business_info set not null,
  alter column ai_enabled set not null,
  alter column google_sheets_webhook_url set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'clients_page_id_key'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients add constraint clients_page_id_key unique (page_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'clients_bot_type_ai_only_check'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients add constraint clients_bot_type_ai_only_check check (bot_type = 'ai');
  end if;
end $$;

create index if not exists clients_created_at_idx
  on public.clients (created_at);
