-- Core client table used by the dashboard, Facebook connection flow, and AI prompt builder.

create extension if not exists pgcrypto;

create table if not exists public.clients (
  id integer generated by default as identity primary key,
  client_name text not null,
  page_id text not null,
  page_access_token text not null,
  created_at timestamptz not null default now(),
  bot_type text not null default 'ai',
  business_info text not null default '',
  ai_enabled boolean not null default true,
  ai_character text not null default '',
  ai_tone text not null default '',
  google_sheets_webhook_url text not null default '',
  google_sheets_tab_name text not null default 'Sheet1',
  lead_capture_fields text not null default 'Full Name
Phone',
  lead_capture_messages text not null default '',
  welcome_sequence_enabled boolean not null default false,
  welcome_message text not null default '',
  welcome_link_url text not null default '',
  welcome_image_urls text not null default '',
  manual_ai_pause_minutes integer not null default 5,
  auto_reply_ignore_pattern text not null default '',
  constraint clients_page_id_key unique (page_id)
);

alter table public.clients
  add column if not exists client_name text,
  add column if not exists page_id text,
  add column if not exists page_access_token text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists bot_type text not null default 'ai',
  add column if not exists business_info text not null default '',
  add column if not exists ai_enabled boolean not null default true,
  add column if not exists ai_character text not null default '',
  add column if not exists ai_tone text not null default '',
  add column if not exists google_sheets_webhook_url text not null default '',
  add column if not exists google_sheets_tab_name text not null default 'Sheet1',
  add column if not exists lead_capture_fields text not null default 'Full Name
Phone',
  add column if not exists lead_capture_messages text not null default '',
  add column if not exists welcome_sequence_enabled boolean not null default false,
  add column if not exists welcome_message text not null default '',
  add column if not exists welcome_link_url text not null default '',
  add column if not exists welcome_image_urls text not null default '',
  add column if not exists manual_ai_pause_minutes integer not null default 5,
  add column if not exists auto_reply_ignore_pattern text not null default '';

update public.clients
set
  client_name = coalesce(client_name, ''),
  page_id = coalesce(page_id, ''),
  page_access_token = coalesce(page_access_token, ''),
  bot_type = 'ai',
  business_info = coalesce(business_info, ''),
  ai_enabled = coalesce(ai_enabled, true),
  ai_character = coalesce(ai_character, ''),
  ai_tone = coalesce(ai_tone, ''),
  google_sheets_webhook_url = coalesce(google_sheets_webhook_url, ''),
  google_sheets_tab_name = coalesce(nullif(google_sheets_tab_name, ''), 'Sheet1'),
  lead_capture_fields = coalesce(nullif(lead_capture_fields, ''), 'Full Name
Phone'),
  lead_capture_messages = coalesce(lead_capture_messages, ''),
  welcome_sequence_enabled = coalesce(welcome_sequence_enabled, false),
  welcome_message = coalesce(welcome_message, ''),
  welcome_link_url = coalesce(welcome_link_url, ''),
  welcome_image_urls = coalesce(welcome_image_urls, ''),
  manual_ai_pause_minutes = coalesce(manual_ai_pause_minutes, 5),
  auto_reply_ignore_pattern = coalesce(auto_reply_ignore_pattern, '');

alter table public.clients
  alter column client_name set not null,
  alter column page_id set not null,
  alter column page_access_token set not null,
  alter column created_at set default now(),
  alter column bot_type set default 'ai',
  alter column business_info set default '',
  alter column ai_enabled set default true,
  alter column ai_character set default '',
  alter column ai_tone set default '',
  alter column google_sheets_webhook_url set default '',
  alter column google_sheets_tab_name set default 'Sheet1',
  alter column lead_capture_fields set default 'Full Name
Phone',
  alter column lead_capture_messages set default '',
  alter column bot_type set not null,
  alter column business_info set not null,
  alter column ai_enabled set not null,
  alter column ai_character set not null,
  alter column ai_tone set not null,
  alter column google_sheets_webhook_url set not null,
  alter column google_sheets_tab_name set not null,
  alter column lead_capture_fields set not null,
  alter column lead_capture_messages set not null,
  alter column welcome_sequence_enabled set default false,
  alter column welcome_message set default '',
  alter column welcome_link_url set default '',
  alter column welcome_image_urls set default '',
  alter column manual_ai_pause_minutes set default 5,
  alter column auto_reply_ignore_pattern set default '',
  alter column welcome_sequence_enabled set not null,
  alter column welcome_message set not null,
  alter column welcome_link_url set not null,
  alter column welcome_image_urls set not null,
  alter column manual_ai_pause_minutes set not null,
  alter column auto_reply_ignore_pattern set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'clients_page_id_key'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients add constraint clients_page_id_key unique (page_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'clients_bot_type_ai_only_check'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients add constraint clients_bot_type_ai_only_check check (bot_type = 'ai');
  end if;
end $$;

create index if not exists clients_created_at_idx
  on public.clients (created_at);
