-- Core tables used by the dashboard, Facebook connection flow, and Full AI prompt builder.
-- Run this first.

create extension if not exists pgcrypto;

create table if not exists public.clients (
  id integer generated by default as identity primary key,
  client_name text not null,
  page_id text not null,
  page_access_token text not null,
  created_at timestamptz not null default now(),
  bot_type text not null default 'ai',
  business_info text not null default '',
  constraint clients_page_id_key unique (page_id)
);

alter table public.clients
  add column if not exists client_name text;

alter table public.clients
  add column if not exists page_id text;

alter table public.clients
  add column if not exists page_access_token text;

alter table public.clients
  add column if not exists created_at timestamptz not null default now();

alter table public.clients
  add column if not exists bot_type text not null default 'ai';

alter table public.clients
  add column if not exists business_info text not null default '';

update public.clients
set client_name = ''
where client_name is null;

update public.clients
set page_id = ''
where page_id is null;

update public.clients
set page_access_token = ''
where page_access_token is null;

alter table public.clients
  alter column client_name set not null;

alter table public.clients
  alter column page_id set not null;

alter table public.clients
  alter column page_access_token set not null;

alter table public.clients
  alter column created_at set default now();

alter table public.clients
  alter column bot_type set default 'ai';

alter table public.clients
  alter column business_info set default '';

update public.clients
set bot_type = 'ai'
where bot_type is distinct from 'ai';

update public.clients
set business_info = ''
where business_info is null;

alter table public.clients
  alter column bot_type set not null;

alter table public.clients
  alter column business_info set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'clients_page_id_key'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients
      add constraint clients_page_id_key unique (page_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'clients_bot_type_ai_only_check'
      and conrelid = 'public.clients'::regclass
  ) then
    alter table public.clients
      add constraint clients_bot_type_ai_only_check check (bot_type = 'ai');
  end if;
end $$;

create index if not exists clients_created_at_idx
  on public.clients (created_at);

create table if not exists public.faqs (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  keywords text[] not null default '{}',
  answer text not null,
  image_attachment_id text,
  created_at timestamptz not null default now()
);

alter table public.faqs
  add column if not exists client_id integer;

alter table public.faqs
  add column if not exists keywords text[] not null default '{}';

alter table public.faqs
  add column if not exists answer text not null default '';

alter table public.faqs
  add column if not exists image_attachment_id text;

alter table public.faqs
  add column if not exists created_at timestamptz not null default now();

create index if not exists faqs_client_created_at_idx
  on public.faqs (client_id, created_at);
