-- Legacy keyword/flow support tables.
-- The current product is Full AI only, but these tables are still referenced by
-- debug/cleanup code and older webhook helper paths. Keep them until the legacy
-- flow APIs are fully removed.

create table if not exists public.bot_flow_reply_sessions (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  waiting_node_id text not null,
  next_node_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bot_flow_reply_sessions_client_recipient_key unique (client_id, recipient_id)
);

alter table public.bot_flow_reply_sessions
  add column if not exists client_id integer;

alter table public.bot_flow_reply_sessions
  add column if not exists page_id text not null default '';

alter table public.bot_flow_reply_sessions
  add column if not exists recipient_id text not null default '';

alter table public.bot_flow_reply_sessions
  add column if not exists waiting_node_id text not null default '';

alter table public.bot_flow_reply_sessions
  add column if not exists next_node_id text not null default '';

alter table public.bot_flow_reply_sessions
  add column if not exists created_at timestamptz not null default now();

alter table public.bot_flow_reply_sessions
  add column if not exists updated_at timestamptz not null default now();

create index if not exists bot_flow_reply_sessions_updated_at_idx
  on public.bot_flow_reply_sessions (updated_at);

create index if not exists bot_flow_reply_sessions_client_updated_at_idx
  on public.bot_flow_reply_sessions (client_id, updated_at desc);
