-- Messenger send/usage logs used by webhook rate-limit handling and the
-- dashboard storage cleanup endpoint.

create table if not exists public.rate_limit_logs (
  id integer generated by default as identity primary key,
  client_id text not null,
  page_id text not null,
  recipient_id text not null,
  message_type text not null,
  attempt_number integer not null default 0,
  status_code integer not null,
  error_code integer,
  error_subcode integer,
  error_message text not null,
  x_app_usage text,
  x_page_usage text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.rate_limit_logs
  add column if not exists client_id text not null default '';

alter table public.rate_limit_logs
  add column if not exists page_id text not null default '';

alter table public.rate_limit_logs
  add column if not exists recipient_id text not null default '';

alter table public.rate_limit_logs
  add column if not exists message_type text not null default '';

alter table public.rate_limit_logs
  add column if not exists attempt_number integer not null default 0;

alter table public.rate_limit_logs
  add column if not exists status_code integer not null default 0;

alter table public.rate_limit_logs
  add column if not exists error_code integer;

alter table public.rate_limit_logs
  add column if not exists error_subcode integer;

alter table public.rate_limit_logs
  add column if not exists error_message text not null default '';

alter table public.rate_limit_logs
  add column if not exists x_app_usage text;

alter table public.rate_limit_logs
  add column if not exists x_page_usage text;

alter table public.rate_limit_logs
  add column if not exists payload jsonb not null default '{}'::jsonb;

alter table public.rate_limit_logs
  add column if not exists created_at timestamptz not null default now();

create index if not exists rate_limit_logs_created_at_idx
  on public.rate_limit_logs (created_at);

create index if not exists rate_limit_logs_client_created_at_idx
  on public.rate_limit_logs (client_id, created_at desc);

create index if not exists rate_limit_logs_page_created_at_idx
  on public.rate_limit_logs (page_id, created_at desc);
