-- Business owner access.
-- Admin users are still controlled by SUPABASE_ADMIN_EMAILS. Business owners
-- are Supabase Auth users whose email appears here and is assigned to a client.

create table if not exists public.business_users (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  email text not null,
  role text not null default 'owner',
  created_at timestamptz not null default now(),
  constraint business_users_email_key unique (email),
  constraint business_users_role_check check (role in ('owner'))
);

alter table public.business_users
  add column if not exists client_id integer;

alter table public.business_users
  add column if not exists email text not null default '';

alter table public.business_users
  add column if not exists role text not null default 'owner';

alter table public.business_users
  add column if not exists created_at timestamptz not null default now();

create index if not exists business_users_client_id_idx
  on public.business_users (client_id);

-- Add business owners like this after creating their Supabase Auth user:
-- insert into public.business_users (client_id, email)
-- values (1, 'owner@example.com')
-- on conflict (email) do update set client_id = excluded.client_id;
