-- Orders table for the business-owner order view.
-- The AI order-taking workflow can insert confirmed orders here later.

create table if not exists public.orders (
  id integer generated by default as identity primary key,
  client_id integer not null references public.clients(id) on delete cascade,
  page_id text not null,
  recipient_id text not null,
  customer_name text,
  contact_number text,
  order_summary text not null,
  status text not null default 'pending',
  total_amount numeric(12, 2),
  payment_method text,
  delivery_method text,
  delivery_address text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_status_check check (status in ('pending', 'confirmed', 'completed', 'cancelled'))
);

alter table public.orders
  add column if not exists client_id integer;

alter table public.orders
  add column if not exists page_id text not null default '';

alter table public.orders
  add column if not exists recipient_id text not null default '';

alter table public.orders
  add column if not exists customer_name text;

alter table public.orders
  add column if not exists contact_number text;

alter table public.orders
  add column if not exists order_summary text not null default '';

alter table public.orders
  add column if not exists status text not null default 'pending';

alter table public.orders
  add column if not exists total_amount numeric(12, 2);

alter table public.orders
  add column if not exists payment_method text;

alter table public.orders
  add column if not exists delivery_method text;

alter table public.orders
  add column if not exists delivery_address text;

alter table public.orders
  add column if not exists notes text;

alter table public.orders
  add column if not exists created_at timestamptz not null default now();

alter table public.orders
  add column if not exists updated_at timestamptz not null default now();

create index if not exists orders_client_created_at_idx
  on public.orders (client_id, created_at desc);

create index if not exists orders_client_status_idx
  on public.orders (client_id, status);
